---
abstract: 'Ad-Hoc reporting from DBIx::Class'
author:
  - "Curtis \"Ovid\" Poe, C<< <ovid at cpan.org> >>"
  - "Curtis \"Ovid\" Poe <ovid@cpan.org>"
build_requires:
  DBD::SQLite: 1.42
  DBIx::Class::Schema::Loader: 0.07037
  ExtUtils::MakeMaker: 6.59
  Test::Most: 0.33
configure_requires:
  ExtUtils::MakeMaker: 6.59
  Module::Install: 0
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: artistic2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class-Report
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  DBIx::Class: 0.08210
  Digest::MD5: 2
  Moose: 2
  namespace::autoclean: 0.20
  perl: 5.6.0
resources:
  bugtracker: https://github.com/Ovid/dbix-class-report/issues
  homepage: https://github.com/Ovid/dbix-class-report
  license: http://www.perlfoundation.org/artistic_license_2_0
  repository: https://github.com/Ovid/dbix-class-report
version: 0.02
